<section>
    <h2><?php $this->getPageTitle() ?></h2>
</section>
<section>
    <?php  if($this->auth->check()) : ?>
    <?php else : ?>
     <?php endif; ?>
    <?php if(isset($this->view->success)): ?>
   	<div class="alert success">
   		<span class="closebtn" onclick="this.parentElement.style.display='none';">&times;</span>
   		<?php echo $this->view->success[0]; ?>
   	</div>
   <?php endif; ?>

   <?php if(isset($this->view->erros)): ?>
   	<div class="alert warning">
   		<span class="closebtn" onclick="this.parentElement.style.display='none';">&times;</span>
   		<?php echo $this->view->errors[0]; ?>
   	</div>
    <?php endif; ?>
    <table class="tbl">
        <thead>
            <tr>
                <td>ID</td>
                <td>Tipo</td>
                <td>Nome</td>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($this->view->components as $component): ?>
            <tr class="<?php echo $component->id; ?>" onclick="window.location='/component/<?php echo $component->id; ?>/show'">
                <td><?php echo $component->id ?></td>
                <td><?php echo $component->code ?></td>
                <td><?php echo $component->name ?></td>
            </tr>
            <?php endforeach; ?>
        </tbody>
        <tfoot>
            <tr>
                <td>ID</td>
                <td>Tipo</td>
                <td>Nome</td>
            </tr>
        </tfoot>
</section>
