<section>
    <h2><?php $this->getPageTitle() ?></h2>
</section>
<section>
    <?php  if($this->auth->check()) : ?>
     <li > <?php echo $this->auth->name() ?> </li>
    <?php else : ?>
     <?php endif; ?>
    ID | Código | Disciplina
    <?php
    //var_dump($this->view->success);
    //var_dump($this->view->errors);
    foreach ($this->view->components as $component): ?>
    <div>
        <a href="/component/<?php echo $component->id;?>/show">
            <?php echo "{$component->id}  | {$component->code} | {$component->name}"; ?>
        </a>
        <?php echo " -- ";?>
        <a href="/component/<?php echo $component->id;?>/edit">Edit</a>
        <?php echo " -- ";?>
        <a href="/component/<?php echo $component->id;?>/delete">Delete</a>
    </div>
    <?php endforeach; ?>
</section>
