<section class="container my-5">
    <div class="card-columns">
    <?php foreach ($this->view->exam as $exam):?>
        <div class="card">
            <img class="card-img-top" src="/<?= $exam->image ?>" width="200px" alt="Card image cap">
            <div class="card-body">
                <h5 class="h5 card-title">Criado em: <?= date('d-m-Y', strtotime($exam->created_at));?></h5>
                <h5 class="h5">Professor: <?= $exam->professor;?></h5>
                <h5 class="h5">Período: <?= $exam->period;?></h5>
                <h5 class="h5">Unidade: <?= $exam->unit;?></h5>
            </div>
        </div>
    <?php endforeach?>
    </div>
    <!-- <table class="datatable table table-striped table-bordered" style="width: 100%">
		<thead>
			<tr>
				<td>Criado em</td>
				<td>Professor</td>
				<td data-priority="1">Período</td>
				<td data-priority="2">Unidade</td>
			</tr>
		</thead>
		<tbody>
			<?php foreach ($this->view->exam as $exam):?>
			<tr onclick="window.location='/exam/<?php echo $exam->id;?>/show'">
				<td><?php echo date('d-m-Y', strtotime($exam->created_at));?></td>
				<td><?php echo $exam->professor;?></td>
				<td><?php echo $exam->period;?></td>
				<td><?php echo $exam->unit;?></td>
			</tr>
			<?php endforeach?>
		</tbody>
	</table> -->
</section>
