<section class="container my-5">
    <table class="datatable table table-striped table-bordered" style="width: 100%">
		<thead>
			<tr>
				<td>Criado em</td>
				<td>Professor</td>
				<td data-priority="1">Período</td>
				<td data-priority="2">Unidade</td>
			</tr>
		</thead>
		<tbody>
			<?php foreach ($this->view->exam as $exam):?>
			<tr onclick="window.location='/exam/<?php echo $exam->id;?>/show'">
				<td><?php echo date('d-m-Y', strtotime($exam->created_at));?></td>
				<td><?php echo $exam->professor;?></td>
				<td><?php echo $exam->period;?></td>
				<td><?php echo $exam->unit;?></td>
			</tr>
			<?php endforeach?>
		</tbody>
	</table>
</section>
