-- MySQL Script generated by MySQL Workbench
-- Thu Mar  1 18:44:34 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`courses`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`courses` ;

CREATE TABLE IF NOT EXISTS `mydb`.`courses` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `type` TINYINT(1) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`users` ;

CREATE TABLE IF NOT EXISTS `mydb`.`users` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `image` VARCHAR(255) NULL,
  `score` INT NOT NULL DEFAULT 0,
  `birthdate` DATE NOT NULL,
  `level` TINYINT(2) NOT NULL,
  `courses_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC),
  INDEX `fk_users_courses_idx` (`courses_id` ASC),
  CONSTRAINT `fk_users_courses`
    FOREIGN KEY (`courses_id`)
    REFERENCES `mydb`.`courses` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`components`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`components` ;

CREATE TABLE IF NOT EXISTS `mydb`.`components` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`exams`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`exams` ;

CREATE TABLE IF NOT EXISTS `mydb`.`exams` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `professor` VARCHAR(100) NOT NULL,
  `period` VARCHAR(15) NOT NULL,
  `created_at` DATE NOT NULL,
  `status` TINYINT(1) NOT NULL DEFAULT 1,
  `components_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_exams_components1_idx` (`components_id` ASC),
  CONSTRAINT `fk_exams_components1`
    FOREIGN KEY (`components_id`)
    REFERENCES `mydb`.`components` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`courses_has_components`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`courses_has_components` ;

CREATE TABLE IF NOT EXISTS `mydb`.`courses_has_components` (
  `courses_id` INT NOT NULL,
  `components_id` INT NOT NULL,
  PRIMARY KEY (`courses_id`, `components_id`),
  INDEX `fk_courses_has_components_components1_idx` (`components_id` ASC),
  INDEX `fk_courses_has_components_courses1_idx` (`courses_id` ASC),
  CONSTRAINT `fk_courses_has_components_courses1`
    FOREIGN KEY (`courses_id`)
    REFERENCES `mydb`.`courses` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_courses_has_components_components1`
    FOREIGN KEY (`components_id`)
    REFERENCES `mydb`.`components` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
