<section class="container my-5">
    <h2 class="text-center mb-5">
        <?php echo $this->getPageTitle() ?>
    </h2>
    <div class="form-center">
        <form action="/user/store" method= "post" accept-charset="utf-8" enctype="multipart/form-data">
            <div class="form-row">
                <div class="form-group col-6">
                    <label for="name">Nome</label><br>
                    <input type="text" id="name" name="name" class="form-control" required>
                </div>

                <div class="form-group col-6">
                    <label for="birthdate">Data de Nascimento</label><br>
                    <input type="date" id="birthdate" name="birthdate" class="form-control" required>
                </div>
            </div>
            <div class="form-group">
                <label for="courses_id">Curso</label><br>
                <select id="courses_id" name="courses_id" class="custom-select" required>
                    <option value=""></option>
                    <?php foreach($this->obj as $course): ?>
                        <option value= <?php echo $course->id; ?> > <?php echo $course->name ?> </option>
                    <?php endforeach; ?>
                </select>
            </div>
            <div class="form-group">
                <label for="email">Email</label><br>
                <input type="email" id="email" name="email" class="form-control" required>
            </div>
            <div class="form-row">
                <div class="form-group col-6">
                    <label for="password">Senha</label><br>
                    <input type="password" id="password" name="password" class="form-control" pattern=".{5,}" maxlength="10" required>
                    <small id="password" class="form-text text-muted">Entre 5 e 10 caracteres</small>
                </div>
                <div class="form-group col-6">
                    <label for="password_confirmation">Senha (confirmação)</label><br>
                    <input type="password" id="password_confirmation" name="password_confirmation" class="form-control" pattern=".{5,}" maxlength="10" required>
                </div>
            </div>
            <div class="custom-file">
                <label for="image" class="custom-file-label">Selecionar Arquivo</label><br>
                <input type="file" class="custom-file-input" id="image" name="image" class="form-control">
            </div>
            <div class="form-group text-right">
                <a href="/users" class="btn">Cancel</a>
                <button type="submit" class="btn btn-lg btn-bdp">Cadastrar</button>
            </div>
        </form>
    </div>
</div>
