<div class="container">
    <h2 class="h2"><?php echo $this->getPageTitle() ?></h2>

    <form action="/user/store" method= "post" accept-charset="utf-8" enctype="multipart/form-data">
    <div class="form-group">
        <label for="name">Nome</label><br>
        <input type="text" name="name" class="form-control" required>
    </div>

    <div class="form-group">
        <label for="birthdate">Data de Nascimento</label><br>
        <input type="date" name="birthdate" class="form-control" required>
    </div>
    <div class="form-group">
        <label for="courses_id">Curso</label><br>
        <select name="courses_id" required>
            <option value=""></option>
            <?php foreach($this->obj as $course): ?>
                <option value= <?php echo $course->id; ?> > <?php echo $course->name ?> </option>
            <?php endforeach; ?>
        </select>
    </div>
    <div class="form-group">
        <label for="email">Email</label><br>
        <input type="email" name="email" class="form-control" required>
    </div>
    <div class="form-group">
        <label for="password">Password (mínimo 5 caracteres, máximo 10)</label><br>
        <input type="password" name="password" class="form-control" pattern=".{5,}" maxlength="10" required>
    </div>
    <div class="form-group">
        <label for="password">Password(confirmação)</label><br>
        <input type="password" name="password_confirmation" class="form-control" pattern=".{5,}" maxlength="10" required>
    </div>
    <div class="form-group">
        <label for="image">Image</label><br>
        <input type="file" name="image" class="form-control" accept=".png, .jpg, .jpeg">
    </div>
    <div class="form-group">
        <a href="/users" class="btn">Cancel</a>
        <button type="submit" class="btn">Cadastrar</button>
    </div>
    </form>
</div>
