<div class="container">
    <h1 class="h1"><?php echo $this->getPageTitle() ?></h1>

    <?php var_dump($this->view->errors); ?>

    <form action="/user/store" method= "post" accept-charset="utf-8" enctype="multipart/form-data">
      <div class="form-group">
        <label for="name">Nome</label>
        <input type="text" name="name" class="form-control" required>
      </div>
     
      <div class="form-group">
        <label for="birthdate">Data de Nascimento</label>
        <input type="date" name="birthdate" class="form-control" required>
      </div>
      <div class="form-group">
          <label for="courses_id">Curso</label>
          <select name="courses_id" required>
              <option value=""></option>
              <?php foreach($this->obj as $course): ?>
                  <option value= <?php echo $course->id; ?> > <?php echo $course->name ?> </option>
              <?php endforeach; ?>
          </select>
      </div>
      <div class="form-group">
          <label for="email">Email</label>
          <input type="email" name="email" class="form-control" required>
      </div>
      <div class="form-group">
          <label for="password">Password (mínimo 5 caracteres, máximo 10)</label>
          <input type="password" name="password" class="form-control" pattern=".{5,}" maxlength="10" required>
      </div>
      <div class="form-group">
          <label for="password">Password(confirmação)</label>
          <input type="password" name="password_confirmation" class="form-control" pattern=".{5,}" maxlength="10" required>
           <div class="form-group">
        <label for="image">Image</label>
        <input type="file" name="image" class="form-control">
      </div>
      </div>
      <a href="/users" class="btn btn-default">Cancel</a>
      <button type="submit" class="btn btn-primary">Save</button>
</div>
