<div class="container">
    <h1 class="h1"><?php echo $this->getPageTitle() ?></h1>

    <form action="/user/<?php echo $this->view->user->id ?>/update" method= "post" accept-charset="utf-8">
      <div class="form-group">
        <label for="name">Nome</label>
        <input type="text" name="name" class="form-control" value="<?php echo $this->view->user->name ?>">
      </div>
      <div class="form-group">
        <label for="email">Email</label>
        <input type="email" name="email" class="form-control" value="<?php echo $this->view->user->email ?>">
      </div>
      <div class="form-group">
        <label for="password">Password</label>
        <input type="password" name="password" class="form-control">
      </div>
      <div class="form-group">
        <label for="image">Image</label>
        <input type="file" name="image" class="form-control" >
      </div>
      <div class="form-group">
        <label for="birthdate">Data de Nascimento</label>
        <input type="date" name="birthdate" class="form-control" value="<?php echo $this->view->user->birthdate ?>">
      </div>
      <div class="form-group">
          <label for="courses_id">Curso</label> <br>
          <?php
          foreach($this->obj as $course){
              echo "<input type='radio' name='courses_id' value=" .  $course->id;
              if($this->view->user->courses_id == $course->id){
                  echo " checked ";
              }
              echo ">";
              echo $course->name . "<br>";
          }
          ?>
      </div>
      <a href="/users" class="btn btn-default">Cancel</a>
      <button type="submit" class="btn btn-primary">Save</button>
</div>
