<div class="container">
    <h1 class="h1"><?php echo $this->getPageTitle() ?></h1>

    <form action="/user/<?php echo $this->view->user->id ?>/update" name="userUpdateForm" method= "post" accept-charset="utf-8" enctype="multipart/form-data">
        <div class="form-group">
            <label for="name">Nome</label>
            <input type="text" name="name" class="form-control" value="<?php echo $this->view->user->name ?>" required>
        </div>

        <div class="form-group">
            <label for="image">Image</label>
            <input type="file" name="image" class="form-control" accept=".png, .jpg, .jpeg">
        </div>
        <div class="form-group">
            <label for="birthdate">Data de Nascimento</label>
            <input type="date" name="birthdate" class="form-control" value="<?php echo $this->view->user->birthdate ?>" required>
        </div>
        <div class="form-group">
            <label for="courses_id">Curso</label> <br>
            <?php
            foreach($this->obj as $course){
                    echo "<input type='radio' name='courses_id' value=" .  $course->id;
                if($this->view->user->courses_id == $course->id){
                    echo " checked ";
                }
                echo ">";
                echo $course->name . "<br>";
            }
            ?>
        </div>
        <div class="form-group">
            <label for="email">Email</label>
            <input type="email" name="email" class="form-control" value="<?php echo $this->view->user->email ?>" required>
        </div>
        <div class="form-group">
            <label for="password">Current Password</label>
            <input type="password" name="password" class="form-control" pattern=".{5,}" maxlength="10" required>
        </div>

        <input type="checkbox" id="pswd_setting" name="new_pswd_setting" onclick="activateInsertion()"/>
            <label for="pswd_setting" class="new_pswd">Set new password</label>
                <div class="form-pswd-group">
                    <label for="new_password" class="pswd-ctrl">New Password (mínimo 5 caracteres, máximo 10)</label> <br>
                    <input type="password" name="new_password" class="pswd-ctrl" pattern=".{5,}" maxlength="10" required disabled> <br>
                    <label for="new_password_confirmation" class="pswd-ctrl">Confirm your new Password</label> <br>
                    <input type="password" name="new_password_confirmation" class="pswd-ctrl" pattern=".{5,}" maxlength="10" required disabled>
                </div>
        <a href="/users" class="btn btn-default">Cancel</a>
        <button type="submit" class="btn btn-primary">Save</button>
    </form>
</div>
