<section>
    <h2> <?php echo $this->view->users->name ?></h2>
</section>
<div class="container">
    <div class="row">
        <ul>
            <li>Nome: <?php echo $this->view->users->name; ?> </li>
            <li>Email: <?php echo $this->view->users->email; ?> </li>
            <li>Data de Nascimento: <?php echo date('d-m-Y', strtotime($this->view->users->birthdate)); ?> </li>
            <li>Score: <?php echo $this->view->users->score; ?> </li>
            <li>ID do Curso: <?php echo $this->view->users->courses_id; ?>
        </ul>
    </div>
</div>
