<section>
    <h1>
        <?php echo $this->getPageTitle(); ?>
    </h1>
</section>

<form action="passwordrecovery" method="post" accept-charset="utf-8">
    <div class="form-group">
        <label for="email">Insira seu Email</label><br>
        <input type="email" name="email" class="form-control" required>
    </div>
    <div class="form-group">
        <label for="email">Confirme seu Email.</label><br>
        <input type="email" name="email_confirmation" class="form-control" required>
    </div>
    <div class="form-group">
        <a href="/" class="btn">Cancel</a>
        <button type="submit" class="btn">Recuperar senha</button>
    </div>
</form>
