<section>
    <h1 class="h1">
        <?php echo $this->getPageTitle(); ?>
        <a href="/user/create" class="bin bin-primary pull-right">
            New User
        </a>
    </h1>
</section>

<div class="container">
<?php  if($this->auth->check()) : ?>
     <li > <?php echo $this->auth->name() ?> </li>
    <?php else : ?>
     <?php endif; ?>

    <?php

    var_dump($this->view->success);
    var_dump($this->view->errors);
    foreach ($this->view->users as $user):?>
    <div class="row">
        <ul>
            <li>Nome: <?php echo $user->name; ?> </li>
            <li>Email: <?php echo $user->email; ?> </li>
            <li>Data de Nascimento: <?php echo date('d-m-Y', strtotime($user->birthdate)); ?> </li>
            <li>Score: <?php echo $user->score; ?> </li>
            <li>ID do Curso: <?php echo $user->courses_id; ?>
            <br/>
        </ul>
        <a href="/user/<?php echo $user->id ?>/edit"> Edit </a>
        <a href="/user/<?php echo $user->id ?>/delete"> Delete </a>
    </div>
<?php endforeach;  ?>
</div>
