<section>
    <h1 class="h1">
        <?php echo $this->getPageTitle(); ?>
        <a href="/user/create" class="bin bin-primary pull-right">
            New User
        </a>
    </h1>
</section>

<div class="container">
<?php  if($this->auth->check()) : ?>
     <li > <?php echo $this->auth->name() ?> </li>
    <?php else : ?>
     <?php endif; ?>
     
     <?php if(isset($this->view->success)): ?>
    <div class="alert success">
        <span class="closebtn" onclick="this.parentElement.style.display='none';">&times;</span>
        <?php echo $this->view->success[0]; ?>
    </div>
<?php endif; ?>

<?php if(isset($this->view->errors)): ?>
    <div class="alert warning">
        <span class="closebtn" onclick="this.parentElement.style.display='none';">&times;</span>
        <?php echo $this->view->errors[0]; ?>
    </div>
<?php endif; ?>


    <?php
    foreach ($this->view->users as $user):?>
    <div class="row">
        <ul>
            <li>Nome: <?php echo $user->name; ?> </li>
            <li>Email: <?php echo $user->email; ?> </li>
            <li>Data de Nascimento: <?php echo date('d-m-Y', strtotime($user->birthdate)); ?> </li>
            <li>Score: <?php echo $user->score; ?> </li>
            <li>ID do Curso: <?php echo $user->courses_id; ?>
            <img src= " <?php echo  $user->image;?> "  width=200 height=200 />
            <?php  echo "<br>"; ?>
            <br/>
        </ul>
        <a href="/user/<?php echo $user->id ?>/edit"> Edit </a>
        <a href="/user/<?php echo $user->id ?>/delete"> Delete </a>
    </div>
<?php endforeach;  ?>
</div>
