<section class="container my-5">
    <h2 class="text-center">Perfil: <?php echo $this->view->users->name ?></h2>
    <div class="d-flex flex-row flex-wrap justify-content-center align-items-center bg-purple rounded my-3 p-3">
        <img class="w-25 profile-img bg-light rounded-circle m-3" src="https://www.freeiconspng.com/uploads/profile-icon-9.png" alt="Imagem de Perfil">
        <div>
            <ul class="list-group list-group-flush">
                <li class="list-group-item">Email: <?php echo $this->view->users->email; ?> </li>
                <li class="list-group-item">Data de Nascimento: <?php echo date('d/m/Y', strtotime($this->view->users->birthdate)); ?> </li>
                <li class="list-group-item">Score: <?php echo $this->view->users->score; ?> </li>
                <li class="list-group-item">ID do Curso: <?php echo $this->view->users->courses_id; ?>
            </ul>
            <div class="d-flex justify-content-center mt-3">
                <button type="button" role="button" class="btn text-center btn-primary">Editar Perfil</button>
                <button type="button" role="button" class="btn btn-sm btn-danger">Deletar Conta</button>
            </div>
        </div>
    </div>
    <hr>
    <h2 class="text-center mt-3">Suas Provas</h2>
    <div class="d-flex flex-row flex-wrap my-3 justify-content-center">
        <?php foreach ($this->view->exams as $exam): ?>
            <div class="box d-flex flex-row flex-wrap align-items-center justify-content-around bg-purple p-2">
                <ul class="list-group w-50 border rounded">
                    <li class="list-group-item">Criada em: <?= date('d/m/Y', strtotime($exam->created_at)); ?></li>
                    <li class="list-group-item">Status: <?= $exam->status ?></li>
                    <li class="list-group-item">Disciplina: <?= $exam->code . " - " . $exam->name ?></li>
                </ul>
                <div>
                    <img src="../../<?=$exam->image?>" class="p-1 thumbnail" alt="Thumbnail da Prova">
                </div>
            </div>
        <?php endforeach; ?>
    </div>
</section>
