<section class="flexbox">
    <?php if(isset($this->view->success)): ?>
    	<div class="alert success">
    		<span class="closebtn" onclick="this.parentElement.style.display='none';">&times;</span>
    		<?php echo $this->view->success[0]; ?>
    	</div>
    <?php endif; ?>

    <?php if(isset($this->view->erros)): ?>
    	<div class="alert warning">
    		<span class="closebtn" onclick="this.parentElement.style.display='none';">&times;</span>
    		<?php echo $this->view->errors[0]; ?>
    	</div>
    <?php endif; ?>
    <?php foreach ($this->view->areas as $area): ?>
    <a href="area/<?php echo $area->id;?>/show"><section class="flex-col txt-center">
        <h2>Área <?php echo $area->id;?></h2>
        <h3><?php echo $area->name;?></h3>
    </section></a>
    <?php endforeach;?>
</section>
