<div class ="container ">

<h1 class ="h1"> <?php echo $this->getPageTitle() ?> </h1>

	<form action = "/area/store" method="post" accept-charset="utf-8">
			<div class = "form-group">
			<label for ="title"> Areas </label> <br>
			<input type = "text" name = "name" class ="form-control">
		</div>
		<a href = "/areas" class ="btn btn-default"> Cancel </a> <br>
		<button type = "submit" class = "btn btn-primary" > Save </button>
	</form>
</div>