<div>

<h1 > <?php echo $this->getPageTitle() ?> </h1>

	<form action = "/area/<?php echo $this->view->area->id?>/update" method="post" accept-charset="utf-8">
		<div class = "form-group">
			<label for ="title"> Area </label> <br>
			<input type = "text" name = "name" value= "<?php echo $this->view->area->name ?>" >
		</div>
		<a href = "/areas"> Cancel </a> <br>
		<button type = "submit"  > Save </button>
	</form>
</div>
