<h2>
	<?php $this->getPageTitle(); ?>
	<a href = "/area/create"> Adicione nova Area</a>
</h2>

<?php if(isset($this->view->success)): ?>
	<div class="alert success">
		<span class="closebtn" onclick="this.parentElement.style.display='none';">&times;</span>
		<?php echo $this->view->success[0]; ?>
	</div>
<?php endif; ?>

<?php if(isset($this->view->errors)): ?>
	<div class="alert warning">
		<span class="closebtn" onclick="this.parentElement.style.display='none';">&times;</span>
		<?php echo $this->view->errors[0]; ?>
	</div>
<?php endif; ?>

<?php
foreach ($this->view->areas as $area): ?>
	<h3 >
		<a href="area/<?php echo $area->id ?>/show">  <?php echo $area->name;?> </a>
	</h3>
	<?php  if($this->auth->level()) : ?>
		<a href = "/area/<?php echo $area->id ?>/edit" > editar </a>
		<a href = "/area/<?php echo $area->id ?>/delete" > excluir </a>
	<?php endif;?>
<?php endforeach;?>
