<section>
	<table class="tbl">
		<thead>
			<tr>
				<td>Nome</td>
				<td>Tipo</td>
				<td>Área</td>
			</tr>
		</thead>
		<tbody>
			<?php foreach ($this->view->areas as $area):?>
			<tr class="<?php echo $area->courses_id;?>" onclick="window.location='/area/<?php echo $area->id;?>/show'">
				<td><?php echo $area->courses_name;?></td>
				<td><?php echo $area->courses_type;?></td>
				<td><?php echo $area->name;?></td>
			</tr>
			<?php endforeach?>
		</tbody>
		<tfoot>
			<tr>
				<td>Nome</td>
				<td>Tipo</td>
				<td>Área</td>
			</tr>
		</tfoot>
	</table>
</section>
