<section class="container my-5">
	<table class="tbl">
		<thead>
			<tr>
				<td>Nome</td>
				<td>Tipo</td>
			</tr>
		</thead>
		<tbody>
			<?php foreach ($this->view->courses as $course):?>
			<tr onclick="window.location='/course/<?php echo $course->id;?>/show'">
				<td><?php echo $course->name;?></td>
				<td><?php echo $course->type;?></td>
			</tr>
			<?php endforeach;?>
		</tbody>
		<tfoot>
			<tr>
				<td>Nome</td>
				<td>Tipo</td>
			</tr>
		</tfoot>
	</table>
</section>
