<div class ="container ">

<h1 class ="h1"> <?php echo $this->getPageTitle() ?> </h1>

	<form action = "/course/store" method="post" accept-charset="utf-8">
		<div class = "form-group">
			<label for ="title"> Course </label> <br>
			<input type = "text" name="name">
		</div>
		<div class="form-group">
			<label for="title" > Type </label><br>
			<input type ="text" name="type"> 
		</div> 
		<div>
			<label for="areas_id" > Area: </label><br>
			<input type="number" name="areas_id"> 
		</div> 
		<a href="/courses">Cancel</a> <br>
		<button type="submit"> Save </button>
	</form>
</div>