<div >

<h1 > <?php echo $this->getPageTitle() ?> </h1>

	<form action = "/course/store" method="post" accept-charset="utf-8">
		<div class = "form-group">
			<label for ="title"> Course </label> <br>
			<input type = "text" name="name">
		</div>
		<div class="form-group">
			<label for="title" > Type </label><br>
			<select name="type">
				<option value="1">Graduação</option>
				<option value="2">Especialização</option>
				<option value="3">Mestrado</option>
				<option value="4">Doutorado</option>
			</select>
		</div>
		<div>
			<label for="areas_id" > Area: </label><br>
			<select name="areas_id">
	            <?php foreach($this->obj as $area): ?>
	                <option value= <?php echo $area->id; ?> > <?php echo $area->name ?> </option>
	            <?php endforeach; ?>
	        </select>
		</div>
		<a href="/courses">Cancel</a> <br>
		<button type="submit"> Save </button>
	</form>
</div>
