<div class ="container ">

<h1 class ="h1"> <?php echo $this->getPageTitle() ?> </h1>

	<form action = "/course/store" method="post" accept-charset="utf-8">
			<div class = "form-group">
			<label for ="title"> Course </label> <br>
			<input type = "text" name = "name" class ="form-control">
		</div>
		<div class ="form-group">
			<label for = "title" > Type </label><br>
			<input type ="text" name="type" class ="form-control" > 
		</div> 
		<a href = "/courses" class ="btn btn-default"> Cancel </a> <br>
		<button type = "submit" class = "btn btn-primary" > Save </button>
	</form>
</div>