<div class ="container ">

<h1 class ="h1"> <?php echo $this->getPageTitle() ?> </h1>

	<form action = "/course/<?php echo $this->view->course->id?>/update" method="post" accept-charset="utf-8">
			<div class = "form-group">
			<label for ="title"> Course </label> <br>
			<input type = "text" name = "name" class ="form-control" value= "<?php echo $this->view->course->name ?>" >
		</div>
		<div class ="form-group">
			<label for = "title" > Type </label><br>
			<input type ="number" name="type" class ="form-control" value="<?php echo $this->view->course->type ?>" >
		</div>
		<div class ="form-group">
			<label for = "title" > Area </label><br>
			<?php
	        foreach($this->obj as $area){
	            echo "<input type='radio' name='areas_id' value=" .  $area->id;
	            if($this->view->course->areas_id == $area->id){
	                echo " checked ";
	            }
	            echo ">";
	            echo $area->name . "<br>";
	        }
	        ?>
		</div>
		<a href = "/courses" class ="btn btn-default"> Cancel </a> <br>
		<button type = "submit" class = "btn btn-primary" > Save </button>
	</form>
</div>
