<div class = "container" >
		<h1 class =" h1">
			<?php $this->getPageTitle(); ?>
			<a href = "/course/create" class="btn btn-primary pull-right"> Adicione o curso </a>
		</h1>
	</div>
	<?php  if($this->auth->check()) : ?>
     <li > <?php echo $this->auth->name() ?> </li>
    <?php else : ?>
     <?php endif; ?>
	
	<?php
	var_dump($this->view->success);
    var_dump($this->view->errors);
	foreach ($this->view->courses as $course): ?>
	<h3 class="h3">
	<a href="course/<?php echo $course->id ?>/show">  <?php echo $course->name;?> </a>
	</h3>
	<p class="text-jutify"> Tipo:
		<?php
		switch($course->type){
			case 1:
				echo "Graduação";
				break;
			case 2:
				echo "Especialização";
				break;
			case 3:
				echo "Mestrado";
				break;
			case 4:
				echo "Doutorado";
				break;
		}?>
	</p>
	<p class="text-jutify">
		<?php
		switch($course->areas_id){
			case 1:
				echo "Exatas";
				break;
			case 2:
				echo "Humanidades";
				break;
			case 3:
				echo "Saúde";
				break;
			case 4:
				echo "Artes";
				break;
			case 5:
				echo "Bacharelado Interdisciplinar";
				break;
		}?>
	</p>
	<a href = "/course/<?php echo $course->id ?>/edit" > editar </a>
	<a href = "/course/<?php echo $course->id ?>/delete" > excluir </a>
    </div>
    </hr>
	<?php endforeach; ?>

</div>
