<section class="container my-5">
	<table class="datatable table table-striped table-bordered" style="width: 100%">
		<thead>
			<tr>
				<td>Código</td>
				<td>Nome</td>
			</tr>
		</thead>
		<tbody>
			<?php foreach ($this->view->components as $component):?>
			<tr onclick="window.location='/component/<?php echo $component->id;?>/show'">
				<td><?php echo $component->code;?></td>
				<td><?php echo $component->name;?></td>
			</tr>
			<?php endforeach?>
		</tbody>
	</table>
</section>
