<div >
    <h1 class = "h1"> <?php echo $this->getPageTitle() ?> </h1>

    <form action="/exam/<?php echo $this->view->exam->id ?>/update" method="post" accept-charset="utf-8" enctype="multipart/form-data">
        <div class="form-group">
            <label for="professor">Professor(a)</label> <br>
            <input type="text" name="professor"  value= "<?php echo $this->view->exam->professor; ?>" required>
        </div>
        <div class="form-group">
            <label for="period">Semestre</label> <br>
            <select name="period" required>
                    <?php
                        foreach($this->periods as $semester){
                            if($this->view->exam->period == $semester){
                                echo    "<option value='" . $semester . "' selected>" . $semester . "</option>";
                            }else {
                                echo    "<option value='" . $semester . "'>" . $semester . "</option>";
                            }
                        }
                    ?>
            </select>
        </div>
        <div class="form-group">
            <label for= "components_id">Componente Curricular</label> <br>
            <select name='components_id' required>
            <?php
                foreach($this->obj as $component){
                    if($this->view->exam->components_id == $component->id){
                        echo    "<option value='" . $component->id . "' selected>" . $component->code . " - " . $component->name . "</option>";
                    }else {
                        echo    "<option value='" . $component->id . "'>" . $component->code . " - " . $component->name . "</option>";
                    }
                }
            ?>
            </select>
        </div>
        <div class="form-group">
            <label for="unit">Unidade</label> <br>
            <select name="unit" required>
                <?php
                for ($i=0; $i <= 7; $i++){
                    if($this->view->exam->unit == ($i + 1) ){
                        echo    "<option value='" . $this->view->exam->unit . "' selected>" . $this->units[$i] . "</option>";
                    }else {
                        echo    "<option value='" . ($i + 1) . "'>" . $this->units[$i] . "</option>";
                    }
                }
                ?>
            </select>
        </div>
        <div class="form-group">
            <label for="status">Status de Aprovação</label> <br>
            <select name="status" >
                <?php
                for ($i=0; $i <= 1; $i++){
                    if($this->view->exam->status == ($i + 1) ){
                        echo    "<option value='" . $this->view->exam->status . "' selected>" . $this->status[$i] . "</option>";
                    }else {
                        echo    "<option value='" . ($i + 1) . "'>" . $this->status[$i] . "</option>";
                    }
                }
                ?>
            </select>
        </div>
        <div class="form-group">
            <label for="image">Imagem</label> <br>
            <input type="file" name="image">
        </div>
        <a href="/exams"><button type="button">Cancelar</button></a>
        <button type="submit">Salvar</button>

    </form>

</div>
