<!DOCTYPE html>
<html lang="pt-br">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, height=device-height, initial-scale=1, maximum-scale=1, user-scalable=no">
        <meta http-equiv="X-UA-Compatible" content="ie=edge">
        <title><?php echo $this->getPageTitle("|"); ?>Banco de Provas</title>
        <link rel="stylesheet" href="/assets/css/style.css">
        <script src="/assets/js/jquery.min.js"></script>
        <script src="/assets/js/datatables.min.js"></script>
        <script src="/assets/js/script.js"></script>
    </head>
    <body>
        <div id="popup-login" class="overlay">
            <a class="cancel" href="#"></a>
            <div class="popup">
                <div class="txt-center">
                    <h2>Login</h2>
                </div><br>
                <a href="#" class="close">&times;</a>
                <form method="post" action="/auth">
                    <div class="form-group">
                        <label for="email">E-Mail:</label><br>
                        <input type="text" name="email" required>
                    </div>
                    <div class="form-group">
                        <label for="password">Senha:</label><br>
                        <input type="password" name="password" required>
                    </div>
                    <?php if(isset($this->view->errors)): ?>
                    	<div class="alert warning">
                    		<span class="closebtn" onclick="this.parentElement.style.display='none';">&times;</span>
                    		<?php echo $this->view->errors[0]; ?>
                    	</div>
                    <?php endif; ?>
                    <div class="form-item box-center">
                        <button class="btn" type="submit">Login</button>
                        <a class="btn" href="/user/create">Cadastre-se</a>
                    </div>
                    <a href="/user/forgot">Esqueceu sua senha?</a>
                </form>
            </div>
        </div>
        <?php require_once __DIR__ . "/menu.phtml";?>
        <?php if(isset($this->view->success)): ?>
            <div class="alert success">
                <span class="closebtn" onclick="this.parentElement.style.display='none';">&times;</span>
                <?php echo $this->view->success[0]; ?>
            </div>
        <?php endif; ?>

        <?php if(isset($this->view->errors)): ?>
            <div class="alert warning">
                <span class="closebtn" onclick="this.parentElement.style.display='none';">&times;</span>
                <?php echo $this->view->errors[0]; ?>
            </div>
        <?php endif; ?>
        <?php $this->content() ?>
    </body>
</html>
