<input type="checkbox"  id="control-menu" />
            <label for="control-menu"    class="control-menu"></label>
            <label for="control-menu"    class="menu-icon"><img src="https://cdn1.iconfinder.com/data/icons/feather-2/24/minus-square-128.png" width=45px></label>

<nav class="menu">
    <ul>
        <li><a href="/">Home</a></li>
        <li><a href="/posts">Posts</a></li>
        <li><a href="/exams">Provas</a></li>
        <!--<li><a href="">Page</a></li>-->
    </ul>
</nav>

<!--
<nav class="menu-cursos">
    <ul>
        <li>Curso 1</li>
        <li>Curso 2</li>
        <li>Curso 3</li>
        <li>Curso 4</li>
        <li>Curso 5</li>
        <li>Curso 6</li>
    </ul>
    <ul>
        <li>Curso 1</li>
        <li>Curso 2</li>
        <li>Curso 3</li>
        <li>Curso 4</li>
        <li>Curso 5</li>
        <li>Curso 6</li>
    </ul>
    <ul>
        <li>Curso 1</li>
        <li>Curso 2</li>
        <li>Curso 3</li>
        <li>Curso 4</li>
        <li>Curso 5</li>
        <li>Curso 6</li>
    </ul>
</nav>
-->
