<header>
    <span class="nav-title"><h1>Banco de Provas</h1></span>
    <nav>
        <ul id="topmenu">
            <li><label for="check"><a>MENU</a></label></li>
        </ul>
        <input type="checkbox" id="check">
        <ul id="menu">
            <li id="search">
                <input type="text" name="search" placeholder="Pesquisa por Código">
                <input type="image" src="/assets/img/lupa.png" alt="Pesquisar" id="lupa">
            </li>
            <li><a href="/">Home</a></li>
            <li><a href="/areas">Áreas</a></li>
            <li><a href="#popup-login">Login</a></li>
        </ul>
        <div>       
        </div>
    </nav>
</header>
